version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
    - run:
        name: Install Java 17
        command: |
          sudo apt-get install openjdk-17-jre
          sudo update-alternatives --auto java
    - checkout
    - run:
        name: Generate cache key
        command: ./cache_checksum.sh /tmp/checksum.txt
    - restore_cache:
        key: gradle-{{ checksum "/tmp/checksum.txt" }}
    - run:
        name: Bootstrap Gradle
        command: ./gradlew --version
    - run:
        name: Check
        command: ./gradlew check
    - store_test_results:
        path: build/test-results
    - save_cache:
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
        key: gradle-{{ checksum "/tmp/checksum.txt" }}

workflows:
  test:
    jobs:
    - test:
        context:
        - github-credentials
