version: 2.1

jobs:
  test:
    # machine is required, docker does not work because of testcontainers
    # see https://www.testcontainers.org/supported_docker_environment/
    machine:
      image: ubuntu-2204:2404:2024.11.1
    steps:
    - run:
        name: Install Java 21
        command: |
          sudo apt-get install openjdk-21-jre
          sudo update-alternatives --auto java
    - checkout
    - run:
        name: Generate cache key
        command: ./cache_checksum.sh /tmp/checksum.txt
    - restore_cache:
        key: gradle-{{ checksum "/tmp/checksum.txt" }}
    - run:
        name: Bootstrap Gradle
        command: ./gradlew --version
    - run:
        name: Check
        command: ./gradlew check
    - store_test_results:
        path: build/test-results
        when: true
    - run:
        name: Verify generated sources committed
        command: git diff --exit-code HEAD --
    - save_cache:
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
        key: gradle-{{ checksum "/tmp/checksum.txt" }}

workflows:
  test:
    jobs:
    - test:
        context:
        - github-credentials
